#!/bin/bash
NAME='Brian Uniacke'
EMAIL='brian.uniacke@smartbox.com'

WORKINGCOPIES='$HOME/workingCopies'
CODE='$HOME/code'
GITHUB='$HOME/code/github'
GITLAB='$HOME/code/gitlab'
DOCKERFILES='$HOME/code/gitlab/dockerfiles'
TERRAFORM='$HOME/code/gitlab/terraform'
CHEF_ROLES='$HOME/code/gitlab/chef/roles'
CHEF_ENVIRONMENTS='$HOME/code/gitlab/chef/environments'
CHEF_HANDLERS='$HOME/code/gitlab/chef/handlers'
CHEF_DATA_BAGS='$HOME/code/gitlab/chef-data-bags'
CHEF_COOKBOOKS='$HOME/code/gitlab/chef-cookbooks'
