#!/bin/bash
sudo apt-add-repository \'[arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\'
sudo apt-add-repository \'http://www.scootersoftware.com/ bcompare4 non-free\'
sudo apt-add-repository \'https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client xenial main\'
sudo apt-add-repository \'http://ie.archive.ubuntu.com/ubuntu/ xenial main restricted\'
sudo apt-add-repository \'http://ie.archive.ubuntu.com/ubuntu/ xenial-updates main restricted\'
sudo apt-add-repository \'http://ie.archive.ubuntu.com/ubuntu/ xenial universe\'
sudo apt-add-repository \'http://ie.archive.ubuntu.com/ubuntu/ xenial-updates universe\'
sudo apt-add-repository \'http://ie.archive.ubuntu.com/ubuntu/ xenial multiverse\'
sudo apt-add-repository \'http://ie.archive.ubuntu.com/ubuntu/ xenial-updates multiverse\'
sudo apt-add-repository \'http://ie.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse\'
sudo apt-add-repository \'http://security.ubuntu.com/ubuntu xenial-security main restricted\'
sudo apt-add-repository \'http://security.ubuntu.com/ubuntu xenial-security universe\'
sudo apt-add-repository \'http://security.ubuntu.com/ubuntu xenial-security multiverse\'
